version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: apkjanimarsya
    container_name: apkjanimarsya-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "80"
    volumes:
      - ./:/var/www/html:rw
      - ./vendor:/var/www/html/vendor:rw
      - ./.env.docker:/var/www/html/.env:rw
    depends_on:
      - db
    networks:
      - apkjanimarsya-network

  db:
    image: mysql:8.0
    container_name: apkjanimarsya-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: apkjanimarsya
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - apkjanimarsya-network

networks:
  apkjanimarsya-network:
    driver: bridge

volumes:
  mysqldata:
    driver: local:rw
